galaxy_info:
  role_name: deploy
  description: Выкладка микросервисов на docker кластер
  author: Leonid
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - all
