---
- name: Установка Docker
  block:
    - name: Добавление universe
      apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
    
    - name: Установка дополнительных пакетов
      apt:
        name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-pip
        update_cache: true
        cache_valid_time: 86400
      
    - name: Добавление ключа Docker
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg
    
    - name: Установка стабильного репозитория Docker
      apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu 
          {{ ansible_distribution_release }} stable
        state: present
        update_cache: true
        filename: docker
    
    - name: Установка Docker
      apt:
        name: docker-ce
        update_cache: true
    
    - name: Проверка, что Docker установлен и запущен
      service:
        name: docker
        state: restarted
        enabled: true
  become: true

- name: Установка дополнительных пакетов python
  block:
    - name:
      pip:
        name: docker

- name: Завершение установки
  block:
    - name:  Добавление пользователя в группу Docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
        #    - name: Перезагрузка
        #      reboot:
  become: true
